export const ADD_EXPERT="ADD_EXPERT";
export const DELETE_EXPERT="DELETE_EXPERT";
export const EDIT_EXPERT="EDIT_EXPERT";
export const SEARCH_EXPERT="SEARCH_EXPERT";
export const SET_ALERT ="SET_ALERT";
export const REMOVE_ALERT ="REMOVE_ALERT";
export const REGISTER_SUCCESS ="REGISTER_SUCCESS";
export const REGISTER_FAIL ="REGISTER_FAIL";
